### ISSUE TITLE
 Integrate Reverb for use as buffer

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/genrl#151]
Update Algorithms to use reverb tables

https://github.com/deepmind/reverb

A stretch goal could be to build pytorch integration for reverb

**Comment by threewisemonkeys-as** [comment]
@Sharad24 I was testing out using two different styles of sampling as we had discussed -
1. Using inbuilt `tf.data.Dataset` support to get batched samples
2. Using `Client.sample()` method and then stacking to build batch

You can see the code [here](https://gist.github.com/threewisemonkeys-as/30fe25072600cf903baa96e591c92eeb). Results for benchmarking
```
Existing ReplayBuffer: Push = 0.00012765422000011312 | Sample = 3.264390999975149e-05
With td dataset: Push = 0.001023654710000119 | Sample = 0.0015271164499998122
With regular reverb sampling: Push = 0.0009734939100002521 | Sample = 0.003991213190000053
```
This is averge time for the pushing to and sampling from the buffer.


Im guessing that the existing buffer is fastest since its a simple single machine test so the overhead of reverb server is there. But comparing between 1 and 2, for pushing 1 is faster and sampling 2 is faster. Probably since `tf.data.Dataset` has a lot of optimisations for creating batches whereas the overhead just makes it slow for pushing. 

Maybe the sampling can be implmented better than what [I am currently doing](https://gist.github.com/threewisemonkeys-as/30fe25072600cf903baa96e591c92eeb#file-compare_reverb_buff-py-L135)?

**Comment by Sharad24** [comment]
I think its ok, because we dont really aim to see a benefit for Reverb in the Single Agent setting, its more aimed towards Distributed Training.

**Comment by Sharad24** [comment]
What are the sizes, etc here?

**Comment by Sharad24** [comment]
While we're at it, it would be good to have an option for specifying if one wants to use the regular ReplayBuffer or Reverb. (i.e., in the case of distributed and single agent training)

**Comment by threewisemonkeys-as** [comment]
> What are the sizes, etc here?

size=100, batch_size=8. Ill try it with larger also



> While we're at it, it would be good to have an option for specifying if one wants to use the regular ReplayBuffer or Reverb. (i.e., in the case of distributed and single agent training)

Yeah, that would be good. I'll add it.


Also lmk what you think of the comparison between 1 and 2. Since there isnt much difference between push times for both but a factor of 2 for sample times, I think we should go with `tf.data.Dataset` route. Thats unless there is a much better way to implemet sampling and batching for 2 than my current method
