### ISSUE TITLE
TOML Integration for Hyperparameters

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/genrl#249]
We need to figure out a way to store hyperparameters. This could be through:

1. JSON
2. YAML
3. Others?

We should see the advantages and disadvantages of each and move ahead.

**Comment by sampreet-arthi** [comment]
YAML is much easier to read and write files in.
JSON is a more standard and accessible format.

I'd personally prefer YAML mainly because it would be less of a pain typing and reading a lot of them

**Comment by Sharad24** [comment]
Yeah, agreed. There might be others too though.

**Comment by sampreet-arthi** [comment]
There is also INI, XML and TOML. XML is too much like HTML and it's hard to edit (or read). We could use INI because it's so simple but TOML is also simple and can be dynamically altered (unlike INI).

TOML has been adopted by Python [PEP 518](https://www.python.org/dev/peps/pep-0518/#file-format) so maybe we could try that. This can be a viable option too.

Check [this](https://www.zionandzion.com/json-vs-xml-vs-toml-vs-cson-vs-yaml/) and [this](https://www.barenakedcoder.com/blog/2020/03/config-files-ini-xml-json-yaml-toml/) for details.

**Comment by Sharad24** [comment]
I feel like TOML is the best choice here. Especially given that PEP has now adopted it.

In regards to TOML vs INI, I think TOML is a bit more evolved version of INI? That is why TOML.

**Comment by sampreet-arthi** [comment]
Yep, so we go ahead with TOML?

**Comment by Sharad24** [comment]
Yeah

**Comment by Het-Shah** [comment]
So currently for hyperparams we are dumping in weights as well and I believe toml is not the best thing to use for that. We should be storing a .pt for that so I am adding two things in checkpoints folder, one will be a toml file and another one will be the weights file.

**Comment by sampreet-arthi** [comment]
The trainer save function does that already?

**Comment by Het-Shah** [comment]
yea so that was to save weights only. I added saving hyperparameters with toml.

**Comment by sampreet-arthi** [comment]
This is done, right? @Het-Shah

**Comment by Sharad24** [comment]
Yes
