### ISSUE TITLE
Trainer Refactoring

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/genrl#263]
cc: @sampreet-arthi 

1. The Training loops, especially in Off Policy Trainer, is very complex. This should be simplified.
2. BanditTrainer uses try, except and finally statements which are dangerous.

The ideal state would be how OnPolicyTrainer is, as of now.

**Comment by sampreet-arthi** [comment]
I've raised a PR (#287 ) for 1. @threewisemonkeys-as do you want me to handle 2 also? I can do it if you don't have any specific ideas for it already.

**Comment by threewisemonkeys-as** [comment]
I can take it up. Actually I was thinking we should add early stopping using keyboard interrupt to all the trainers. Since `try` `except` is not the best way, I was thinking somethings like https://stackoverflow.com/questions/32922909/how-to-stop-an-infinite-loop-safely-in-python

**Comment by sampreet-arthi** [comment]
I think you should raise a separate issue for early stopping. We can add that to all trainers. I'm not exactly sure what you mean by early stopping over here (I'm assuming you mean the exception is caught and the rest of the code runs)

On a similar note, I was also considering a way to stop training automatically once it stabilises. For example, if we have `m = mean(agent.log.rewards)` and `v = var(agent.log.rewards` we could impose a condition like:
```
if m > min_reward and v < min_variance:
    print("Early stopping as reward has stagnated")
    break
```
Could be loss instead of reward too. Haven't worked it out though. 

For this issue though, I think refactoring should be enough so that the code is cleaner and easier to understand.

**Comment by Sharad24** [comment]
> I can take it up. Actually I was thinking we should add early stopping using keyboard interrupt to all the trainers. Since `try` `except` is not the best way, I was thinking somethings like https://stackoverflow.com/questions/32922909/how-to-stop-an-infinite-loop-safely-in-python

The problem is not really `try`, `except`, etc., but the fact that we are depending on a keyboard interrupt. Early Stopping should come through metrics, not interrupt signals. Since this is part of the core of the library it has to be extendible, and not runnable.

In the latter case, maybe you'd want to have these things.

**Comment by sampreet-arthi** [comment]
Looks like this had been solved
